#!/usr/bin/env python

# decodehtmlentities: Decode using the htmlentitiesdecode module
# Copyright (C) 2010  Niels Serup

# This program is free software: you can redistribute it and/or modify
# it under the terms of the Do What The Fuck You Want To Public
# License as published by Sam Hocevar, either version 2 of the
# License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the Do
# What The Fuck You Want To Public License for more details.
#
# You should have received a copy of the Do What The Fuck You Want To
# Public License along with this program. If not, see
# <http://sam.zoy.org/wtfpl/>.

# Version:..... 0.1.0
# Maintainer:.. Niels Serup <ns@metanohi.org>


# This is a Python program.
import sys
from htmlentitiesdecode import decode

print decode(' '.join(sys.argv[1:]))
